# pyproject.toml

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "deeprankcore"
version = "0.1.1"
description = "deeprank-core allows to train graph neural networks to classify protein-protein interface with a greater flexibility for the user."
readme = "README.md"
authors = [{ name = "Giulia Crocioni", email = "g.crocioni@esciencecenter.nl" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["graph neural network", "protein-protein interface", "pytorch"]
dependencies = [
    "numpy >= 1.21.5",
    "scipy >= 1.7.3",
    "h5py >= 3.6.0",
    "networkx >= 2.6.3",
    "matplotlib >= 3.5.1",
    "pdb2sql >= 0.5.1",
    "scikit-learn",
    "chart-studio >= 1.1.0",
    "biopython >= 1.79",
    "python-louvain >= 0.16",
    "markov-clustering >= 0.0.6.dev0",
    "tqdm >= 4.63.0",
    "freesasa >= 2.1.0",
    "tensorboard >= 2.9.0",
    "protobuf == 3.20.1",
    "torch-cluster>=1.6.0",
    "torch-sparse>=0.6.13",
    "torch-scatter>=2.0.9",
    "torch-spline-conv>=1.2.1"
]
requires-python = ">=3.9"

[project.optional-dependencies]
dev = ["yapf", "isort"]
doc = ["recommonmark", "sphinx", "sphinx_rtd_theme"]
test = [
    "prospector[with_pyroma]",
    "coverage",
    "pycodestyle",
    "pytest",
    "vpytest-cov",
    "pytest-runner",
    "coveralls"
]

[project.urls]
Homepage = "https://github.com/DeepRank/deeprank-core"

[tool.bumpver]
current_version = "0.1.1"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "Bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"', 'version = "{version}"'
]
"deeprankcore/__init__.py" = ["{version}"]