name: linting

on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    name: Linting build

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Check style against standards using prospector
        run: prospector