name: linting

on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    name: Linting build

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [3.9]

    steps:
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.version }}
          conda-channels: anaconda
      - run: conda --version
      - run: which python

      - name: Install the package
        run: pip install .[test]
        env:
          CONDA_PREFIX: /usr/share/miniconda

      - name: Check style against standards using prospector
        run: prospector